### PR TITLE
added max-retries, new output option, and docs

### PR DESCRIPTION
**Pull request by MendyLanda**

### CODE REVIEW

**Comment by YuviGold** [comment]
Hi @MendyLanda thank you for your PR!

Currently, the GPT model is running with 0 temperature by design to be consistent, 
https://github.com/YuviGold/project_euler_gpt_tester/blob/main/project_euler_gpt_tester/api.py#L11
so there are no different results each run.

In order to make the retries valuable, we should make the temperature configurable from the CLI as well to amplify creativity. Could you do that?

**Comment by MendyLanda** [comment]
Hi @YuviGold, Thanks for pointing that out.

I'm thinking that we should spread the range of the temperature based on the number of tries.
If the user want to select specific temperature, we'll use his instead. 

like so
```max-retries 1```
will run with default 0 temperature
```max-retries 2```
runs with temperatures: 0, 1
```max-retries 3```
0,0.5,1
```max-retries 3 temperature 0.5```
0.5,0.5,0.5 // overriden 

And so on...

What do you think?

**Comment by YuviGold** [comment]
SGTM. 
Please don't delete the `cog` code and how to generate the docs section and we can merge.

**Comment by MendyLanda** [comment]
Sorry about the `cog` code. I did the readme changes extremely quickly and did not think too much before removing it. If I remember correctly I thought it was generated by copilot by accident 🙈.

Anyway, it's back as well as the docs generation.

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
